### ISSUE TITLE
error in batch_size is bigger than 1

### ISSUE THREAD

**Issue by pypi20200320** [jaime-choi/Training-Segment-Anything-Model#1]
when batch_size is bigger than 1, than get the error:

Traceback (most recent call last):
  File "segment_anything/my_train.py", line 213, in <module>
    main()
  File "segment_anything/my_train.py", line 209, in main
    train_sam(cfg, model, optimizer, scheduler, train_data, val_data)
  File "segment_anything/my_train.py", line 77, in train_sam
    bboxes = torch.stack(bboxes, dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [2, 4] at entry 0 and [1, 4] at entry 1

**Comment by Dandelion404** [comment]
It is related to the issue in the official code of SAM. 
See [here](https://github.com/facebookresearch/segment-anything/issues/277#issue-1679935136)
